<a href="https://colab.research.google.com/github/Jeevan-Neupane/PyTorch/blob/main/01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(torch.__version__)

2.5.0+cu121


## Tensor

In [ ]:
#scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector

vector = torch.tensor([7,7]);
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector2d=torch.tensor([[1,2],[2,3],[3,3],[4,4]]);
vector2d

tensor([[1, 2],
        [2, 3],
        [3, 3],
        [4, 4]])

In [ ]:
vector2d.ndim

2

In [ ]:
vector2d.shape

torch.Size([4, 2])

In [ ]:
matrix3d= torch.tensor([[[1,2,3],[4,5,5]],[[23,4,5],[4,3,2]]]);
matrix3d


tensor([[[ 1,  2,  3],
         [ 4,  5,  5]],

        [[23,  4,  5],
         [ 4,  3,  2]]])

In [ ]:
matrix3d.shape

torch.Size([2, 2, 3])

In [ ]:

# 2D tensor (matrix) with 3 rows and 2 columns
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("2D Tensor (Matrix):")
print(matrix)
print("Shape:", matrix.shape)

2D Tensor (Matrix):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])


In [ ]:
tensor_3d = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print("\n3D Tensor:")
print(tensor_3d)
print("Shape:", tensor_3d.shape)


3D Tensor:
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])
Shape: torch.Size([2, 3, 2])


## Random Tensor

In [ ]:
random_tensor= torch.rand(1,2,3)
random_tensor

tensor([[[0.7676, 0.2181, 0.2105],
         [0.9322, 0.4719, 0.2200]]])

In [ ]:
random_tensor.ndim

3

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4));
zeros.dtype


torch.float32

In [ ]:
ones=torch.ones(size=(3,4));
ones,ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Range of tensor and tensor-like

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1);
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros= torch.zeros_like(input=one_to_ten);
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tensor_with_zeros= torch.zeros_like(input=tensor_3d)
tensor_with_zeros

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]])

### Tensoro Datatypes

In [ ]:
#Float 32 Tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape , float_32_tensor.dtype , float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16);
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8967, 0.9681, 0.9928, 0.1211],
        [0.4300, 0.7930, 0.3647, 0.5203],
        [0.0303, 0.9215, 0.0160, 0.2119]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
#32 bit integer

integer_32_tensor = torch.tensor([3,4,5],
                                 dtype=torch.int32)

integer_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
integer_32_tensor*float_32_tensor

tensor([ 9., 24., 45.])

### Tensor Datatype

In [ ]:
import torch

# 32-bit floating-point tensor (default for floats)
tensor_float32 = torch.tensor([1.5, 2.5], dtype=torch.float32)
print("Float32:", tensor_float32, tensor_float32.dtype)

# 64-bit floating-point tensor
tensor_float64 = torch.tensor([1.5, 2.5], dtype=torch.float64)
print("Float64:", tensor_float64, tensor_float64.dtype)

# 16-bit floating-point tensor
tensor_float16 = torch.tensor([1.5, 2.5], dtype=torch.float16)
print("Float16:", tensor_float16, tensor_float16.dtype)

# 64-bit integer tensor (default for integers)
tensor_int64 = torch.tensor([1, 2], dtype=torch.int64)
print("Int64:", tensor_int64, tensor_int64.dtype)

# 8-bit unsigned integer tensor
tensor_uint8 = torch.tensor([1, 2], dtype=torch.uint8)
print("UInt8:", tensor_uint8, tensor_uint8.dtype)

# Boolean tensor
tensor_bool = torch.tensor([True, False, True], dtype=torch.bool)
print("Bool:", tensor_bool, tensor_bool.dtype)


Float32: tensor([1.5000, 2.5000]) torch.float32
Float64: tensor([1.5000, 2.5000], dtype=torch.float64) torch.float64
Float16: tensor([1.5000, 2.5000], dtype=torch.float16) torch.float16
Int64: tensor([1, 2]) torch.int64
UInt8: tensor([1, 2], dtype=torch.uint8) torch.uint8
Bool: tensor([ True, False,  True]) torch.bool


### Getting Information from Tensor

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU


tensor([[0.2282, 0.7749, 0.1502, 0.9368],
        [0.7496, 0.2653, 0.0660, 0.4424],
        [0.7279, 0.3668, 0.7178, 0.8776]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

Device: cpu


In [ ]:
some_tensor=some_tensor.to("cuda");
some_tensor.device

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### Manipulating Tensors

 #### Addition

In [ ]:
tensor= torch.tensor([1,2,3]);

tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

**Reassignment only change the actual value**

In [ ]:
tensor = tensor-10
tensor


tensor([-9, -8, -7])

In [ ]:
tensor=tensor+10

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication

In [ ]:
tensor= torch.tensor([1,2,3]);
tensor.shape

torch.Size([3])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

##### Not working condition

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2));

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
print(torch.matmul(torch.rand(3,2),torch.rand(2,3)))

tensor([[0.3491, 0.3754, 0.3639],
        [0.3792, 0.4488, 0.3673],
        [0.1813, 0.1647, 0.2097]])


#### One of the  error in DL is that it is a  ``shape`` error``

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

> Solution is transpose of one of the matrix

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max , mean , sum , etc (tensor aggregation)

In [ ]:
x=torch.arange(0,100,10);
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Finding the position in tensor that has the minimum value with argmin()

x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Changing shape of tensors

### 1. Reshaping

In [ ]:
import torch

x=torch.arange(1.,10.);
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped= x.reshape(1,1,9)
x_reshaped,x_reshaped.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

### 2. Viewing

In [ ]:
z= x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z will change x since both of them share same memory

z[:,0]=5;
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x,x.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### 3.Stacking

In [ ]:
x_stacked= torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
x_reshaped.shape

torch.Size([1, 1, 9])

In [ ]:
x_reshaped=x_reshaped.squeeze()

In [ ]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 9])

In [ ]:
import torch

# Original 1D tensor
x = torch.tensor([5, 10, 15])
print("Original shape:", x.shape)


Original shape: torch.Size([3])


In [ ]:
x_reshaped = x.unsqueeze(dim=1)
print("Shape after unsqueeze(dim=0):", x_reshaped.shape)


Shape after unsqueeze(dim=0): torch.Size([3, 1])


### Permute

In [ ]:
x_original = torch.rand(224,224,3);

x_permute = x_original.permute(2,0,1);

print(f"x_original : {x_original.shape}");
print(f"New shape:{x_permute.shape}")

x_original : torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [ ]:
x_permute[0][0][0]=760

In [ ]:
x_original[0][0][0]

tensor(760.)

###  Indexing(Selecting data from tensors)

In [ ]:
import torch
x= torch.arange(1,10).reshape(1,3,3);

x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

### Pytorch Tensors and Numpy

In [ ]:
import torch
import numpy as np

In [ ]:
array= np.arange(1.0,8.0);
array.dtype


dtype('float64')

In [ ]:
#convert numpy nd array to tensor

tensor = torch.from_numpy(array);
tensor.dtype

torch.float64

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32);
tensor.dtype

torch.float32

In [ ]:
# Tensor to numpy

tensor =torch.ones(7);
numpy_tensor= tensor.numpy();
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility  (obtain the same results every time you run your code)

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4602, 0.0398, 0.6241, 0.4628],
        [0.5803, 0.1935, 0.8081, 0.1248],
        [0.0878, 0.1563, 0.6920, 0.5153]])

Tensor B:
tensor([[0.1359, 0.1828, 0.1937, 0.8084],
        [0.5791, 0.3401, 0.6740, 0.2423],
        [0.1480, 0.2014, 0.7978, 0.6416]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#Reproducible tensors

import torch

RANDOM_SEED=42;

torch.manual_seed(RANDOM_SEED);

random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED);
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

random_tensor_C==random_tensor_D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running Tensor on GPU

In [ ]:
!nvidia-smi

Sat Nov  2 02:55:45 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2.Check for GPU access with pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code

device="cuda" if torch.cuda.is_available() else "cpu"

device



'cuda'

In [ ]:
torch.cuda.device_count()

1

### 3. Putting Tensors ( and models) on GPU

In [ ]:
tensor = torch.tensor([1,2,3]);
tensor.device

device(type='cpu')

In [ ]:
# Move tensor to GPU (if available)

tensor_on_gpu= tensor.to(device);
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU



In [ ]:
#if tensor is in gput can't transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')