<a href="https://colab.research.google.com/github/Jeevan-Neupane/PyTorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.5.1+cu121


## Introductions to tensor

>### Creating Tensor

In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([1,2,3])

In [ ]:
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]]);


In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor

TENSOR= torch.tensor([[[1,2,3],[43,5,6],[2,4,5]]]);
TENSOR

tensor([[[ 1,  2,  3],
         [43,  5,  6],
         [ 2,  4,  5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

> ### Random Tensor

In [ ]:
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.5546, 0.9145, 0.3519],
        [0.3664, 0.2693, 0.8219],
        [0.9111, 0.3127, 0.2868]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#Image representation using tensor
random_iamge_tensor= torch.rand(size=(3,224,224))

In [ ]:
random_iamge_tensor.ndim

3

In [ ]:
random_iamge_tensor.shape

torch.Size([3, 224, 224])

> ### Zeroes And Ones

In [ ]:
## Tensor with all zeroes

zeros = torch.zeros(size=(3,4));
zeros, zeros.ndim , zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.float32)

In [ ]:
## Creating the tensor of all ones
ones = torch.ones(size=(3,4));
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

> ### Creating a range and tensor like

In [ ]:
zeros_to_ten = torch.arange(start=0, end=10, step=1);
zeros_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros= torch.zeros_like(zeros_to_ten);
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> ### Tensor Datatypes

In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],dtype=None, device=None, requires_grad=False) ;
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor= torch.tensor([3.0,6.0,9.0],dtype=torch.float16, device=None, requires_grad=False) ;
float_16_tensor.dtype

torch.float16

## Getting Information from Tensor

In [2]:
some_tensor = torch.rand(size=(3,4))

In [3]:
some_tensor

tensor([[0.7951, 0.9267, 0.1887, 0.1569],
        [0.7335, 0.6107, 0.4217, 0.4028],
        [0.6828, 0.6557, 0.0746, 0.8320]])

In [5]:
## To get size
some_tensor.shape, some_tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [6]:
## To know which datatype
some_tensor.dtype

torch.float32

In [7]:
## To know which device it is running

some_tensor.device

device(type='cpu')

In [4]:
## To change device

some_tensor_one= torch.rand(size=(3,4),device="cuda");
some_tensor_one

tensor([[0.7843, 0.3922, 0.8845, 0.1658],
        [0.3034, 0.8845, 0.1653, 0.3831],
        [0.6138, 0.1772, 0.7714, 0.4951]], device='cuda:0')

## Tensor Operation

In [2]:
tensor = torch.tensor([1,2,3]);
tensor

tensor([1, 2, 3])

In [3]:
tensor+10

tensor([11, 12, 13])

In [4]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [5]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [6]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [7]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

## Multipliation in Tensor

In [9]:
## Element wise

tensor = torch.tensor([1,2,3]);

tensor*tensor

tensor([1, 4, 9])

In [10]:
torch.matmul(tensor,tensor)

tensor(14)

## Shape Error During Matrix Multiplication

In [18]:
import torch

# Use torch.randint to generate random integers within a specified range
tensor_A = torch.randint(0, 10, size=(3, 2), dtype=torch.int32)  # Generate integers between 0 and 9
tensor_B = torch.randint(0, 10, size=(3, 3), dtype=torch.int32)  # Generate integers between 0 and 9

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [22]:
import torch

# Use torch.randint to generate random integers within a specified range
tensor_A = torch.randint(0, 10, size=(3, 2), dtype=torch.int32)  # Generate integers between 0 and 9
tensor_B = torch.randint(0, 10, size=(3,2), dtype=torch.int32)  # Generate integers between 0 and 9

torch.mm (tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [24]:
tensor_B.T.shape

torch.Size([2, 3])

In [26]:
tensor_B.shape

torch.Size([3, 2])

In [27]:
torch.mm(tensor_A, tensor_B.T)

tensor([[44, 60, 24],
        [64, 88, 32],
        [41, 57, 18]], dtype=torch.int32)

## Aggregation

In [29]:
x= torch.arange(0,100,10);
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
x.min()

tensor(0)

In [31]:
x.max()

tensor(90)

In [34]:
x.type(torch.float32).mean()

tensor(45.)

In [35]:
x.sum()

tensor(450)

## Positional Min/Max

In [36]:
x= torch.arange(0,100,10);
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
x.argmin()

tensor(0)

In [38]:
x.argmax()

tensor(9)

## Change Tensor Datatype

In [39]:
tensor = torch.arange(10.,100.,10.);
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [40]:
tensor_float_16= tensor.type(torch.float16);
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

## Reshaping stacking squeezing and unsqueezing

### Reshaping

In [41]:
x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
x.reshape(3,3) ## size multiplication should give total elements

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

### View

In [44]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
z= x.view(1,9);
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
x.shape

torch.Size([9])

In [50]:
z[:,0]=3

In [51]:
z

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
x

tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])

### Stack

In [55]:
x_stacked = torch.stack([x,x,x,x],dim=1);
x_stacked

tensor([[3., 3., 3., 3.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [56]:
x_stacked.shape

torch.Size([9, 4])

### Squeeze and Unsqueeze

In [58]:
x_stacked.squeeze().shape

torch.Size([9, 4])

In [59]:
## This removes the dimension of one
x= torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [66]:
y=x.squeeze()

In [67]:
y.shape

torch.Size([2, 2, 2])

In [72]:
z= y.unsqueeze(dim=1)

In [73]:
z.shape

torch.Size([2, 1, 2, 2])

### Permute

In [74]:
image_tensor = torch.rand(size=(224,224,3));
image_tensor.shape

torch.Size([224, 224, 3])

In [75]:
image_tensor_permute = image_tensor.permute(2,0,1);

image_tensor_permute.shape

torch.Size([3, 224, 224])