<a href="https://colab.research.google.com/github/Jeevan-Neupane/PyTorch/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.5.1+cu121


## Introductions to tensor

>### Creating Tensor

In [5]:
scalar = torch.tensor(7)

In [6]:
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [12]:
#Vector
vector = torch.tensor([1,2,3])

In [13]:
vector

tensor([1, 2, 3])

In [14]:
vector.ndim

1

In [15]:
vector.item()

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [16]:
vector.shape

torch.Size([3])

In [18]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]]);


In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
#Tensor

TENSOR= torch.tensor([[[1,2,3],[43,5,6],[2,4,5]]]);
TENSOR

tensor([[[ 1,  2,  3],
         [43,  5,  6],
         [ 2,  4,  5]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

> ### Random Tensor

In [27]:
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.5546, 0.9145, 0.3519],
        [0.3664, 0.2693, 0.8219],
        [0.9111, 0.3127, 0.2868]])

In [28]:
random_tensor.dtype

torch.float32

In [30]:
#Image representation using tensor
random_iamge_tensor= torch.rand(size=(3,224,224))

In [31]:
random_iamge_tensor.ndim

3

In [32]:
random_iamge_tensor.shape

torch.Size([3, 224, 224])

> ### Zeroes And Ones

In [34]:
## Tensor with all zeroes

zeros = torch.zeros(size=(3,4));
zeros, zeros.ndim , zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.float32)

In [35]:
## Creating the tensor of all ones
ones = torch.ones(size=(3,4));
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

> ### Creating a range and tensor like

In [37]:
zeros_to_ten = torch.arange(start=0, end=10, step=1);
zeros_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
ten_zeros= torch.zeros_like(zeros_to_ten);
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> ### Tensor Datatypes

In [43]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],dtype=None, device=None, requires_grad=False) ;
float_32_tensor.dtype

torch.float32

In [46]:
float_16_tensor= torch.tensor([3.0,6.0,9.0],dtype=torch.float16, device=None, requires_grad=False) ;
float_16_tensor.dtype

torch.float16